# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build NodeJS Docker app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Send ntfy.sh message
        run: curl -d "Building new Research image..." ntfy.sh/marcus-build?title=GithubActionsRunner

      - name: Clone source code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . -t cnit581malware/baseline:latest
      - name: Send ntfy.sh message
        run: curl -d "New Research image complete." ntfy.sh/marcus-build?title=GithubActionsRunner

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Send ntfy.sh message
        run: curl -d "Pushing new Research image..." ntfy.sh/marcus-build?title=GithubActionsRunner
      - name: Authenticate Docker Hub Account
        run: docker login --username ${{ secrets.DH_USERNAME }} --password ${{ secrets.DH_PASSWORD }}
      - name: Push Docker image
        run: docker push cnit581malware/baseline:latest
      - name: Send ntfy.sh message
        run: curl -d "Successfully pushed Research image..." ntfy.sh/marcus-build?title=GithubActionsRunner